// DO NOT EDIT - Generated by xtask

@import AudioToolbox;
@import Foundation;
#include "BeamerAuBridge.h"

@class {{WRAPPER_CLASS}};

@interface {{WRAPPER_CLASS}} : AUAudioUnit
- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError**)outError;
@end

@interface {{EXTENSION_CLASS}} : NSObject <AUAudioUnitFactory>
@end

@implementation {{EXTENSION_CLASS}}

- (void)beginRequestWithExtensionContext:(NSExtensionContext *)context {
    (void)context;
}

- (AUAudioUnit *)createAudioUnitWithComponentDescription:(AudioComponentDescription)desc
                                                   error:(NSError **)error {
    if (!beamer_au_ensure_factory_registered()) {
        if (error) {
            *error = [NSError errorWithDomain:NSOSStatusErrorDomain
                                         code:kAudioUnitErr_FailedInitialization
                                     userInfo:@{NSLocalizedDescriptionKey: @"Failed to register plugin factory"}];
        }
        return nil;
    }

    return [[{{WRAPPER_CLASS}} alloc] initWithComponentDescription:desc options:0 error:error];
}

@end

void beamer_au_appex_force_link(void) {
    (void)[{{EXTENSION_CLASS}} class];
}

void* {{FACTORY_FUNC}}(const AudioComponentDescription* desc) {
    if (!beamer_au_ensure_factory_registered()) {
        return NULL;
    }
    NSError* error = nil;
    {{WRAPPER_CLASS}}* wrapper = [[{{WRAPPER_CLASS}} alloc] initWithComponentDescription:*desc
                                                                             options:0
                                                                               error:&error];
    if (error) {
        return NULL;
    }
    return (__bridge_retained void*)wrapper;
}
