//! Build tooling for Beamer plugins.
//!
//! Usage: cargo xtask bundle <package> [--vst3] [--au] [--release] [--install] [--clean]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Configuration for creating appex Info.plist
struct AppexPlistConfig<'a> {
    package: &'a str,
    executable_name: &'a str,
    component_type: &'a str,
    manufacturer: Option<&'a str>,
    subtype: Option<&'a str>,
    framework_bundle_id: &'a str,
    version_string: &'a str,
    version_int: u32,
}

// =============================================================================
// ObjC Code Generation
// =============================================================================

/// Convert plugin name to PascalCase for class names.
/// "simple-gain" → "SimpleGain"
fn to_pascal_case(name: &str) -> String {
    name.split(['-', '_'])
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

/// Generate the AU wrapper ObjC implementation with plugin-specific class names.
fn generate_au_wrapper_source(plugin_name: &str) -> String {
    let pascal_name = to_pascal_case(plugin_name);
    let wrapper_class = format!("Beamer{}AuWrapper", pascal_name);

    format!(r#"// Auto-generated AU wrapper for {plugin_name}
// DO NOT EDIT - Generated by xtask

#import <AudioToolbox/AudioToolbox.h>
#import <AVFoundation/AVFoundation.h>
#import <Foundation/Foundation.h>

#include "BeamerAuBridge.h"

// =============================================================================
// MARK: - Debug Logging
// =============================================================================

#define AU_DEBUG(fmt, ...) ((void)0)

// =============================================================================
// MARK: - Constants
// =============================================================================

static const double kDefaultSampleRate = 44100.0;
static const AUAudioFrameCount kDefaultMaxFrames = 4096;

// =============================================================================
// MARK: - {wrapper_class} Interface
// =============================================================================

@interface {wrapper_class} : AUAudioUnit {{
    BeamerAuInstanceHandle _rustInstance;
    NSLock* _instanceLock;
    BOOL _instanceValid;
    AUAudioUnitBusArray* _inputBusArray;
    AUAudioUnitBusArray* _outputBusArray;
    AUParameterTree* _parameterTree;
    BeamerAuSampleFormat _sampleFormat;
    double _sampleRate;
    AUAudioFrameCount _maxFrames;
    BOOL _resourcesAllocated;
    BeamerAuBusConfig _busConfig;
    NSUInteger _instanceId;
    AVAudioPCMBuffer* _inputPCMBuffer;
    AudioBufferList* _inputMutableABL;
    AUAudioUnitPreset* _currentPreset;
}}

+ (NSUInteger)nextInstanceId;

@end

static NSUInteger {wrapper_class}InstanceCounter = 0;

// =============================================================================
// MARK: - {wrapper_class} Implementation
// =============================================================================

@implementation {wrapper_class}

+ (NSUInteger)nextInstanceId {{
    @synchronized([{wrapper_class} class]) {{
        return ++{wrapper_class}InstanceCounter;
    }}
}}

- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError**)outError {{
    NSUInteger instanceId = [[self class] nextInstanceId];

    if (!beamer_au_ensure_factory_registered()) {{
        if (outError != NULL) {{
            *outError = [NSError errorWithDomain:NSOSStatusErrorDomain
                                            code:kAudioUnitErr_FailedInitialization
                                        userInfo:@{{NSLocalizedDescriptionKey: @"Failed to register Rust plugin factory"}}];
        }}
        return nil;
    }}

    self = [super initWithComponentDescription:componentDescription
                                       options:options
                                         error:outError];

    if (self == nil) {{
        return nil;
    }}

    if (outError != NULL) {{
        *outError = nil;
    }}

    _instanceId = instanceId;
    _rustInstance = NULL;
    _instanceLock = [[NSLock alloc] init];
    _instanceValid = NO;
    _inputBusArray = nil;
    _outputBusArray = nil;
    _parameterTree = nil;
    _sampleFormat = BeamerAuSampleFormatFloat32;
    _sampleRate = kDefaultSampleRate;
    _maxFrames = kDefaultMaxFrames;
    _resourcesAllocated = NO;
    memset(&_busConfig, 0, sizeof(_busConfig));

    AUAudioUnitPreset* defaultPreset = [[AUAudioUnitPreset alloc] init];
    defaultPreset.number = 0;
    defaultPreset.name = @"Default";
    _currentPreset = defaultPreset;

    _rustInstance = beamer_au_create_instance();
    if (_rustInstance == NULL) {{
        if (outError != NULL) {{
            *outError = [NSError errorWithDomain:NSOSStatusErrorDomain
                                            code:kAudioUnitErr_FailedInitialization
                                        userInfo:@{{NSLocalizedDescriptionKey: @"Failed to create Rust plugin instance"}}];
        }}
        return nil;
    }}

    _instanceValid = YES;

    if (![self setupBusArraysWithError:outError]) {{
        _instanceValid = NO;
        beamer_au_destroy_instance(_rustInstance);
        _rustInstance = NULL;
        return nil;
    }}

    return self;
}}

- (void)dealloc {{
    [_instanceLock lock];
    _instanceValid = NO;

    if (_rustInstance != NULL) {{
        if (_resourcesAllocated) {{
            beamer_au_deallocate_render_resources(_rustInstance);
            _resourcesAllocated = NO;
        }}
        beamer_au_destroy_instance(_rustInstance);
        _rustInstance = NULL;
    }}

    [_instanceLock unlock];
}}

// -----------------------------------------------------------------------------
// MARK: Bus Configuration
// -----------------------------------------------------------------------------

- (AUAudioUnitBus*)createBusAtIndex:(uint32_t)index
                            isInput:(BOOL)isInput
                      defaultFormat:(AVAudioFormat*)defaultFormat
                              error:(NSError**)outError {{
    uint32_t channelCount = isInput
        ? beamer_au_get_input_bus_channel_count(_rustInstance, index)
        : beamer_au_get_output_bus_channel_count(_rustInstance, index);

    if (channelCount == 0) channelCount = 2;
    if (channelCount > BEAMER_AU_MAX_CHANNELS) channelCount = BEAMER_AU_MAX_CHANNELS;

    AVAudioFormat* format = [[AVAudioFormat alloc]
        initStandardFormatWithSampleRate:kDefaultSampleRate
                                channels:(AVAudioChannelCount)channelCount];
    if (format == nil) {{
        format = defaultFormat;
    }}

    NSError* busError = nil;
    AUAudioUnitBus* bus = [[AUAudioUnitBus alloc] initWithFormat:format error:&busError];
    if (bus == nil) {{
        if (outError != NULL) {{
            *outError = busError;
        }}
        return nil;
    }}

    bus.maximumChannelCount = BEAMER_AU_MAX_CHANNELS;

    if (isInput) {{
        bus.name = (index == 0) ? @"Main Input" : [NSString stringWithFormat:@"Aux Input %u", index];
    }} else {{
        bus.name = (index == 0) ? @"Main Output" : [NSString stringWithFormat:@"Aux Output %u", index];
    }}

    return bus;
}}

- (BOOL)setupBusArraysWithError:(NSError**)outError {{
    if (_rustInstance == NULL) {{
        if (outError != NULL) {{
            *outError = [NSError errorWithDomain:NSOSStatusErrorDomain
                                            code:kAudioUnitErr_Uninitialized
                                        userInfo:@{{NSLocalizedDescriptionKey: @"Rust instance not initialized"}}];
        }}
        return NO;
    }}

    uint32_t inputBusCount = beamer_au_get_input_bus_count(_rustInstance);
    uint32_t outputBusCount = beamer_au_get_output_bus_count(_rustInstance);

    if (inputBusCount > BEAMER_AU_MAX_BUSES) inputBusCount = BEAMER_AU_MAX_BUSES;
    if (outputBusCount > BEAMER_AU_MAX_BUSES) outputBusCount = BEAMER_AU_MAX_BUSES;

    if (inputBusCount == 0 && outputBusCount == 0) {{
        outputBusCount = 1;
    }}

    AVAudioFormat* stereoFormat = [[AVAudioFormat alloc]
        initStandardFormatWithSampleRate:kDefaultSampleRate
                                channels:2];

    NSMutableArray<AUAudioUnitBus*>* inputBuses = [[NSMutableArray alloc] initWithCapacity:inputBusCount];
    for (uint32_t i = 0; i < inputBusCount; i++) {{
        AUAudioUnitBus* bus = [self createBusAtIndex:i
                                             isInput:YES
                                       defaultFormat:stereoFormat
                                               error:outError];
        if (bus == nil) {{
            return NO;
        }}
        [inputBuses addObject:bus];
    }}

    NSMutableArray<AUAudioUnitBus*>* outputBuses = [[NSMutableArray alloc] initWithCapacity:outputBusCount];
    for (uint32_t i = 0; i < outputBusCount; i++) {{
        AUAudioUnitBus* bus = [self createBusAtIndex:i
                                             isInput:NO
                                       defaultFormat:stereoFormat
                                               error:outError];
        if (bus == nil) {{
            return NO;
        }}
        [outputBuses addObject:bus];
    }}

    _inputBusArray = [[AUAudioUnitBusArray alloc] initWithAudioUnit:self
                                                           busType:AUAudioUnitBusTypeInput
                                                            busses:inputBuses];
    _outputBusArray = [[AUAudioUnitBusArray alloc] initWithAudioUnit:self
                                                            busType:AUAudioUnitBusTypeOutput
                                                             busses:outputBuses];

    return YES;
}}

- (void)buildBusConfig {{
    memset(&_busConfig, 0, sizeof(_busConfig));

    _busConfig.input_bus_count = (uint32_t)_inputBusArray.count;
    for (uint32_t i = 0; i < _busConfig.input_bus_count && i < BEAMER_AU_MAX_BUSES; i++) {{
        _busConfig.input_buses[i].channel_count = (uint32_t)_inputBusArray[i].format.channelCount;
        _busConfig.input_buses[i].bus_type = (i == 0) ? BeamerAuBusTypeMain : BeamerAuBusTypeAuxiliary;
    }}

    _busConfig.output_bus_count = (uint32_t)_outputBusArray.count;
    for (uint32_t i = 0; i < _busConfig.output_bus_count && i < BEAMER_AU_MAX_BUSES; i++) {{
        _busConfig.output_buses[i].channel_count = (uint32_t)_outputBusArray[i].format.channelCount;
        _busConfig.output_buses[i].bus_type = (i == 0) ? BeamerAuBusTypeMain : BeamerAuBusTypeAuxiliary;
    }}
}}

// -----------------------------------------------------------------------------
// MARK: Bus Properties
// -----------------------------------------------------------------------------

- (AUAudioUnitBusArray*)inputBusses {{
    return _inputBusArray;
}}

- (AUAudioUnitBusArray*)outputBusses {{
    return _outputBusArray;
}}

// -----------------------------------------------------------------------------
// MARK: Render Resources
// -----------------------------------------------------------------------------

- (BOOL)allocateRenderResourcesAndReturnError:(NSError**)outError {{
    if (_rustInstance == NULL) {{
        if (outError != NULL) {{
            *outError = [NSError errorWithDomain:NSOSStatusErrorDomain
                                            code:kAudioUnitErr_Uninitialized
                                        userInfo:@{{NSLocalizedDescriptionKey: @"Rust instance not initialized"}}];
        }}
        return NO;
    }}

    if (![super allocateRenderResourcesAndReturnError:outError]) {{
        return NO;
    }}

    [self buildBusConfig];

    uint32_t mainInputChannels = (_busConfig.input_bus_count > 0) ? _busConfig.input_buses[0].channel_count : 0;
    uint32_t mainOutputChannels = (_busConfig.output_bus_count > 0) ? _busConfig.output_buses[0].channel_count : 0;

    if (!beamer_au_is_channel_config_valid(_rustInstance, mainInputChannels, mainOutputChannels)) {{
        if (outError != NULL) {{
            *outError = [NSError errorWithDomain:NSOSStatusErrorDomain
                                            code:kAudioUnitErr_FormatNotSupported
                                        userInfo:@{{NSLocalizedDescriptionKey: @"Channel configuration not supported"}}];
        }}
        self.renderResourcesAllocated = NO;
        [super deallocateRenderResources];
        return NO;
    }}

    AVAudioFormat* format = nil;
    if (_outputBusArray.count > 0) {{
        format = _outputBusArray[0].format;
    }} else if (_inputBusArray.count > 0) {{
        format = _inputBusArray[0].format;
    }}

    if (format != nil) {{
        _sampleRate = format.sampleRate;
        _sampleFormat = (format.commonFormat == AVAudioPCMFormatFloat64)
            ? BeamerAuSampleFormatFloat64
            : BeamerAuSampleFormatFloat32;
    }} else {{
        _sampleRate = kDefaultSampleRate;
        _sampleFormat = BeamerAuSampleFormatFloat32;
    }}

    _maxFrames = self.maximumFramesToRender;
    if (_maxFrames == 0) {{
        _maxFrames = kDefaultMaxFrames;
    }}

    if (_inputBusArray.count > 0) {{
        AVAudioFormat* inputFormat = _inputBusArray[0].format;
        _inputPCMBuffer = [[AVAudioPCMBuffer alloc] initWithPCMFormat:inputFormat
                                                       frameCapacity:_maxFrames];
        if (_inputPCMBuffer != nil) {{
            _inputMutableABL = _inputPCMBuffer.mutableAudioBufferList;
        }}
    }}

    OSStatus result = beamer_au_allocate_render_resources(
        _rustInstance,
        _sampleRate,
        _maxFrames,
        _sampleFormat,
        &_busConfig
    );

    if (result != noErr) {{
        if (outError != NULL) {{
            *outError = [NSError errorWithDomain:NSOSStatusErrorDomain
                                            code:result
                                        userInfo:@{{NSLocalizedDescriptionKey: @"Failed to allocate Rust render resources"}}];
        }}
        [super deallocateRenderResources];
        return NO;
    }}

    _resourcesAllocated = YES;
    return YES;
}}

- (void)deallocateRenderResources {{
    _inputMutableABL = NULL;
    _inputPCMBuffer = nil;

    if (_rustInstance != NULL && _resourcesAllocated) {{
        beamer_au_deallocate_render_resources(_rustInstance);
        _resourcesAllocated = NO;
    }}

    [super deallocateRenderResources];
}}

// -----------------------------------------------------------------------------
// MARK: Render Block
// -----------------------------------------------------------------------------

- (AUInternalRenderBlock)internalRenderBlock {{
    BeamerAuInstanceHandle rustInstance = _rustInstance;
    AUHostMusicalContextBlock musicalContext = self.musicalContextBlock;
    AUHostTransportStateBlock transportState = self.transportStateBlock;
    AUScheduleMIDIEventBlock scheduleMIDI = self.scheduleMIDIEventBlock;

    AVAudioPCMBuffer* inputPCMBuffer = _inputPCMBuffer;
    AudioBufferList* inputMutableABL = _inputMutableABL;
    AUAudioFrameCount maxFrames = _maxFrames;

    return ^AUAudioUnitStatus(
        AudioUnitRenderActionFlags* actionFlags,
        const AudioTimeStamp* timestamp,
        AUAudioFrameCount frameCount,
        NSInteger outputBusNumber,
        AudioBufferList* outputData,
        const AURenderEvent* realtimeEventListHead,
        AURenderPullInputBlock __unsafe_unretained pullInputBlock
    ) {{
        if (rustInstance == NULL) {{
            return kAudioUnitErr_Uninitialized;
        }}

        AudioBufferList* inputData = NULL;
        if (inputPCMBuffer != nil && inputMutableABL != NULL && pullInputBlock != nil
            && frameCount <= maxFrames) {{
            const AudioBufferList* originalABL = inputPCMBuffer.audioBufferList;
            UInt32 byteSize = frameCount * sizeof(float);

            inputMutableABL->mNumberBuffers = originalABL->mNumberBuffers;
            for (UInt32 i = 0; i < originalABL->mNumberBuffers; ++i) {{
                inputMutableABL->mBuffers[i].mNumberChannels = originalABL->mBuffers[i].mNumberChannels;
                inputMutableABL->mBuffers[i].mData = originalABL->mBuffers[i].mData;
                inputMutableABL->mBuffers[i].mDataByteSize = byteSize;
            }}

            AudioUnitRenderActionFlags pullFlags = 0;
            AUAudioUnitStatus pullStatus = pullInputBlock(&pullFlags, timestamp, frameCount, 0, inputMutableABL);
            if (pullStatus == noErr) {{
                inputData = inputMutableABL;
            }}
        }}

        return beamer_au_render(
            rustInstance,
            actionFlags,
            timestamp,
            frameCount,
            outputBusNumber,
            outputData,
            realtimeEventListHead,
            pullInputBlock,
            inputData,
            musicalContext,
            transportState,
            scheduleMIDI
        );
    }};
}}

// -----------------------------------------------------------------------------
// MARK: Parameters
// -----------------------------------------------------------------------------

- (AUParameterTree*)parameterTree {{
    if (_parameterTree == nil) {{
        [self buildParameterTree];
    }}
    return _parameterTree;
}}

- (void)buildParameterTree {{
    if (_rustInstance == NULL) {{
        _parameterTree = nil;
        return;
    }}

    uint32_t paramCount = beamer_au_get_parameter_count(_rustInstance);

    if (paramCount == 0) {{
        _parameterTree = [AUParameterTree createTreeWithChildren:@[]];
        return;
    }}

    NSMutableArray<AUParameterNode*>* parameters = [[NSMutableArray alloc] initWithCapacity:paramCount];

    for (uint32_t i = 0; i < paramCount; i++) {{
        BeamerAuParameterInfo info;
        if (!beamer_au_get_parameter_info(_rustInstance, i, &info)) {{
            continue;
        }}

        NSString* identifier = [NSString stringWithFormat:@"param_%u", info.id];
        NSString* name = [NSString stringWithUTF8String:info.name];
        AudioUnitParameterUnit auUnit = [self auUnitFromUnitsString:info.units];

        AudioUnitParameterOptions flags = kAudioUnitParameterFlag_IsReadable;
        if (!(info.flags & BeamerAuParameterFlagReadOnly)) {{
            flags |= kAudioUnitParameterFlag_IsWritable;
        }}

        AUParameter* param = [AUParameterTree createParameterWithIdentifier:identifier
                                                                       name:name
                                                                    address:(AUParameterAddress)info.id
                                                                        min:0.0f
                                                                        max:1.0f
                                                                       unit:auUnit
                                                                   unitName:nil
                                                                      flags:flags
                                                               valueStrings:nil
                                                        dependentParameters:nil];

        param.value = info.default_value;
        [parameters addObject:param];
    }}

    _parameterTree = [AUParameterTree createTreeWithChildren:parameters];
    [self setupParameterCallbacks];
}}

- (void)setupParameterCallbacks {{
    if (_parameterTree == nil || _rustInstance == NULL) {{
        return;
    }}

    __weak typeof(self) weakSelf = self;

    _parameterTree.implementorValueProvider = ^AUValue(AUParameter* param) {{
        __strong typeof(self) strongSelf = weakSelf;
        if (strongSelf == nil) {{
            return 0.0f;
        }}

        [strongSelf->_instanceLock lock];
        AUValue result = 0.0f;
        if (strongSelf->_instanceValid && strongSelf->_rustInstance != NULL) {{
            result = beamer_au_get_parameter_value(strongSelf->_rustInstance, (uint32_t)param.address);
        }}
        [strongSelf->_instanceLock unlock];
        return result;
    }};

    _parameterTree.implementorValueObserver = ^(AUParameter* param, AUValue value) {{
        __strong typeof(self) strongSelf = weakSelf;
        if (strongSelf == nil) {{
            return;
        }}

        [strongSelf->_instanceLock lock];
        if (strongSelf->_instanceValid && strongSelf->_rustInstance != NULL) {{
            beamer_au_set_parameter_value(strongSelf->_rustInstance, (uint32_t)param.address, value);
        }}
        [strongSelf->_instanceLock unlock];
    }};

    _parameterTree.implementorStringFromValueCallback = ^NSString* _Nonnull(AUParameter* param, const AUValue* value) {{
        __strong typeof(self) strongSelf = weakSelf;
        AUValue displayValue = (value != NULL) ? *value : param.value;

        if (strongSelf == nil) {{
            return [NSString stringWithFormat:@"%.2f", displayValue];
        }}

        [strongSelf->_instanceLock lock];
        NSString* result = nil;
        if (strongSelf->_instanceValid && strongSelf->_rustInstance != NULL) {{
            char buffer[128];
            uint32_t written = beamer_au_format_parameter_value(
                strongSelf->_rustInstance,
                (uint32_t)param.address,
                displayValue,
                buffer,
                sizeof(buffer)
            );
            if (written > 0) {{
                result = [NSString stringWithUTF8String:buffer];
            }}
        }}
        [strongSelf->_instanceLock unlock];

        return (result != nil) ? result : [NSString stringWithFormat:@"%.2f", displayValue];
    }};

    _parameterTree.implementorValueFromStringCallback = ^AUValue(AUParameter* param, NSString* string) {{
        __strong typeof(self) strongSelf = weakSelf;
        if (strongSelf == nil || string == nil) {{
            return param.value;
        }}

        [strongSelf->_instanceLock lock];
        AUValue result = param.value;
        if (strongSelf->_instanceValid && strongSelf->_rustInstance != NULL) {{
            float parsedValue = 0.0f;
            if (beamer_au_parse_parameter_value(strongSelf->_rustInstance, (uint32_t)param.address, string.UTF8String, &parsedValue)) {{
                result = parsedValue;
            }}
        }}
        [strongSelf->_instanceLock unlock];
        return result;
    }};
}}

- (AudioUnitParameterUnit)auUnitFromUnitsString:(const char*)units {{
    if (units == NULL || units[0] == '\0') {{
        return kAudioUnitParameterUnit_Generic;
    }}

    NSString* unitStr = [[NSString stringWithUTF8String:units] lowercaseString];

    if ([unitStr isEqualToString:@"db"] || [unitStr isEqualToString:@"decibels"]) {{
        return kAudioUnitParameterUnit_Decibels;
    }} else if ([unitStr isEqualToString:@"hz"] || [unitStr isEqualToString:@"hertz"]) {{
        return kAudioUnitParameterUnit_Hertz;
    }} else if ([unitStr isEqualToString:@"ms"] || [unitStr isEqualToString:@"milliseconds"]) {{
        return kAudioUnitParameterUnit_Milliseconds;
    }} else if ([unitStr isEqualToString:@"s"] || [unitStr isEqualToString:@"seconds"]) {{
        return kAudioUnitParameterUnit_Seconds;
    }} else if ([unitStr isEqualToString:@"%"] || [unitStr isEqualToString:@"percent"]) {{
        return kAudioUnitParameterUnit_Percent;
    }} else if ([unitStr isEqualToString:@"pan"]) {{
        return kAudioUnitParameterUnit_Pan;
    }} else if ([unitStr isEqualToString:@"ratio"]) {{
        return kAudioUnitParameterUnit_Ratio;
    }} else if ([unitStr isEqualToString:@"bpm"]) {{
        return kAudioUnitParameterUnit_BPM;
    }} else if ([unitStr isEqualToString:@"semitones"]) {{
        return kAudioUnitParameterUnit_RelativeSemiTones;
    }} else if ([unitStr isEqualToString:@"cents"]) {{
        return kAudioUnitParameterUnit_Cents;
    }} else if ([unitStr isEqualToString:@"octaves"]) {{
        return kAudioUnitParameterUnit_Octaves;
    }} else if ([unitStr isEqualToString:@"degrees"]) {{
        return kAudioUnitParameterUnit_Degrees;
    }}

    return kAudioUnitParameterUnit_Generic;
}}

// -----------------------------------------------------------------------------
// MARK: State Persistence
// -----------------------------------------------------------------------------

- (NSDictionary<NSString*, id>*)fullState {{
    NSMutableDictionary* state = [[super fullState] mutableCopy];
    if (state == nil) {{
        state = [[NSMutableDictionary alloc] init];
    }}

    if (_rustInstance != NULL) {{
        uint32_t stateSize = beamer_au_get_state_size(_rustInstance);
        if (stateSize > 0) {{
            uint8_t* buffer = (uint8_t*)malloc(stateSize);
            if (buffer != NULL) {{
                uint32_t written = beamer_au_get_state(_rustInstance, buffer, stateSize);
                if (written > 0) {{
                    NSData* stateData = [NSData dataWithBytes:buffer length:written];
                    state[@"beamerState"] = stateData;
                }}
                free(buffer);
            }}
        }}
    }}

    return state;
}}

- (void)setFullState:(NSDictionary<NSString*, id>*)fullState {{
    [super setFullState:fullState];

    if (_rustInstance != NULL && fullState != nil) {{
        NSData* stateData = fullState[@"beamerState"];
        if (stateData != nil && stateData.length > 0) {{
            OSStatus status = beamer_au_set_state(_rustInstance, stateData.bytes, (uint32_t)stateData.length);

            if (status != noErr) {{
                return;
            }}

            if (_parameterTree != nil) {{
                for (AUParameter* param in _parameterTree.allParameters) {{
                    AUValue newValue = beamer_au_get_parameter_value(_rustInstance, (uint32_t)param.address);
                    [param setValue:newValue originator:nil];
                }}
            }}
        }}
    }}
}}

// -----------------------------------------------------------------------------
// MARK: Preset Properties
// -----------------------------------------------------------------------------

- (AUAudioUnitPreset*)currentPreset {{
    return _currentPreset;
}}

- (void)setCurrentPreset:(AUAudioUnitPreset*)currentPreset {{
    if (currentPreset == nil) {{
        _currentPreset = nil;
        return;
    }}
    _currentPreset = currentPreset;
}}

- (NSArray<AUAudioUnitPreset*>*)factoryPresets {{
    static NSArray<AUAudioUnitPreset*>* presets = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{{
        AUAudioUnitPreset* defaultPreset = [[AUAudioUnitPreset alloc] init];
        defaultPreset.number = 0;
        defaultPreset.name = @"Default";
        presets = @[defaultPreset];
    }});
    return presets;
}}

// -----------------------------------------------------------------------------
// MARK: Processing Properties
// -----------------------------------------------------------------------------

- (NSTimeInterval)latency {{
    if (_rustInstance == NULL || _sampleRate <= 0.0) {{
        return 0.0;
    }}
    uint32_t latencySamples = beamer_au_get_latency_samples(_rustInstance);
    return (NSTimeInterval)latencySamples / _sampleRate;
}}

- (NSTimeInterval)tailTime {{
    if (_rustInstance == NULL || _sampleRate <= 0.0) {{
        return 0.0;
    }}
    uint32_t tailSamples = beamer_au_get_tail_samples(_rustInstance);
    if (tailSamples == UINT32_MAX) {{
        return INFINITY;
    }}
    return (NSTimeInterval)tailSamples / _sampleRate;
}}

- (BOOL)supportsMPE {{
    return NO;
}}

- (BOOL)supportsUserPresets {{
    return YES;
}}

- (NSArray<NSNumber*>*)channelCapabilities {{
    return nil;
}}

- (void)reset {{
    if (_rustInstance != NULL) {{
        beamer_au_reset(_rustInstance);
    }}
}}

- (BOOL)canProcessInPlace {{
    return NO;
}}

@end
"#, plugin_name = plugin_name, wrapper_class = wrapper_class)
}

/// Generate the AU extension ObjC implementation with plugin-specific class names.
/// The extension class implements AUAudioUnitFactory protocol for AU instantiation.
fn generate_au_extension_source(plugin_name: &str) -> String {
    let pascal_name = to_pascal_case(plugin_name);
    let wrapper_class = format!("Beamer{}AuWrapper", pascal_name);
    let extension_class = format!("Beamer{}AuExtension", pascal_name);
    let factory_func = format!("Beamer{}AuExtensionFactory", pascal_name);

    format!(r#"// Auto-generated AU extension for {plugin_name}
// DO NOT EDIT - Generated by xtask

#import <AudioToolbox/AudioToolbox.h>
#import <Foundation/Foundation.h>
#include "BeamerAuBridge.h"

@class {wrapper_class};

@interface {wrapper_class} : AUAudioUnit
- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError**)outError;
@end

// Extension class implementing AUAudioUnitFactory protocol.
// NSExtensionMain instantiates this class based on NSExtensionPrincipalClass in Info.plist.
@interface {extension_class} : NSObject <AUAudioUnitFactory>
@end

@implementation {extension_class}

// Required by NSExtensionRequestHandling protocol, but not used for AUv3.
// NSExtensionMain calls createAudioUnitWithComponentDescription:error: directly.
- (void)beginRequestWithExtensionContext:(NSExtensionContext *)context {{
    (void)context;
}}

- (nullable AUAudioUnit *)createAudioUnitWithComponentDescription:(AudioComponentDescription)desc
                                                            error:(NSError **)error {{
    if (!beamer_au_ensure_factory_registered()) {{
        if (error) {{
            *error = [NSError errorWithDomain:NSOSStatusErrorDomain
                                         code:kAudioUnitErr_FailedInitialization
                                     userInfo:@{{NSLocalizedDescriptionKey: @"Failed to register plugin factory"}}];
        }}
        return nil;
    }}
    return [[{wrapper_class} alloc] initWithComponentDescription:desc options:0 error:error];
}}

@end

// Generic force_link function called by Rust code to ensure ObjC classes are linked.
// This is internal to each plugin's dylib, so no symbol collision occurs.
void beamer_au_appex_force_link(void) {{
    (void)[{extension_class} class];
}}

void* {factory_func}(const AudioComponentDescription* desc) {{
    if (!beamer_au_ensure_factory_registered()) {{
        return NULL;
    }}
    NSError* error = nil;
    {wrapper_class}* wrapper = [[{wrapper_class} alloc] initWithComponentDescription:*desc
                                                                             options:0
                                                                               error:&error];
    if (error) {{
        return NULL;
    }}
    return (__bridge_retained void*)wrapper;
}}
"#, plugin_name = plugin_name,
    wrapper_class = wrapper_class,
    extension_class = extension_class,
    factory_func = factory_func)
}

/// Generate appex_stub.m for the plugin.
/// This is a minimal stub - the actual entry point is NSExtensionMain (via -e linker flag).
/// The framework link in the clang command ensures the framework is loaded.
fn generate_appex_stub_source(plugin_name: &str) -> String {
    format!(r#"// Auto-generated appex stub for {plugin_name}
// DO NOT EDIT - Generated by xtask
//
// This file does NOT contain main(). The entry point is NSExtensionMain,
// which is set via the -e _NSExtensionMain linker flag. NSExtensionMain
// handles all XPC setup for app extensions automatically.
//
// The framework is linked via -framework flag, which ensures it's loaded.
// NSExtensionMain reads NSExtensionPrincipalClass from Info.plist and
// instantiates the extension class from the framework.

#import <Foundation/Foundation.h>

// Minimal stub - just needs to compile to create an object file.
// The -framework link ensures our AU framework is loaded at runtime.
"#, plugin_name = plugin_name)
}

/// Generate and compile plugin-specific ObjC code.
///
/// This creates uniquely named ObjC classes for each plugin to avoid symbol collisions
/// when multiple AU plugins are loaded in the same process (e.g., in Reaper).
///
/// Returns the path to the directory containing the compiled static libraries.
fn compile_plugin_objc(
    plugin_name: &str,
    workspace_root: &Path,
    target: &str,
) -> Result<PathBuf, String> {
    let lib_name = plugin_name.replace('-', "_");

    // Create output directory for generated sources and compiled libraries
    let gen_dir = workspace_root
        .join("target")
        .join("au-gen")
        .join(plugin_name)
        .join(target);

    fs::create_dir_all(&gen_dir)
        .map_err(|e| format!("Failed to create au-gen directory: {}", e))?;

    // Generate plugin-specific ObjC source files
    let wrapper_source = generate_au_wrapper_source(plugin_name);
    let extension_source = generate_au_extension_source(plugin_name);

    let wrapper_path = gen_dir.join("AuWrapper.m");
    let extension_path = gen_dir.join("AuExtension.m");

    fs::write(&wrapper_path, wrapper_source)
        .map_err(|e| format!("Failed to write AuWrapper.m: {}", e))?;
    fs::write(&extension_path, extension_source)
        .map_err(|e| format!("Failed to write AuExtension.m: {}", e))?;

    // Path to BeamerAuBridge.h header
    let bridge_header_dir = workspace_root.join("crates/beamer-au/objc");

    // Determine architecture for clang
    let arch = match target {
        "x86_64-apple-darwin" => "x86_64",
        "aarch64-apple-darwin" => "arm64",
        _ => return Err(format!("Unsupported target: {}", target)),
    };

    // Compile AuWrapper.m to static library
    let wrapper_obj = gen_dir.join("AuWrapper.o");
    let wrapper_lib = gen_dir.join(format!("lib{}_au_objc.a", lib_name));

    let status = Command::new("clang")
        .args([
            "-c",
            "-arch", arch,
            "-fobjc-arc",
            "-fmodules",
            "-I", bridge_header_dir.to_str().unwrap(),
            "-o", wrapper_obj.to_str().unwrap(),
            wrapper_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to compile AuWrapper.m: {}", e))?;

    if !status.success() {
        return Err("Failed to compile AuWrapper.m".to_string());
    }

    // Create static library from object file
    let status = Command::new("ar")
        .args(["rcs", wrapper_lib.to_str().unwrap(), wrapper_obj.to_str().unwrap()])
        .status()
        .map_err(|e| format!("Failed to create static library: {}", e))?;

    if !status.success() {
        return Err("Failed to create AuWrapper static library".to_string());
    }

    // Compile AuExtension.m to static library
    let extension_obj = gen_dir.join("AuExtension.o");
    let extension_lib = gen_dir.join(format!("lib{}_au_extension.a", lib_name));

    let status = Command::new("clang")
        .args([
            "-c",
            "-arch", arch,
            "-fobjc-arc",
            "-fmodules",
            "-I", bridge_header_dir.to_str().unwrap(),
            "-o", extension_obj.to_str().unwrap(),
            extension_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to compile AuExtension.m: {}", e))?;

    if !status.success() {
        return Err("Failed to compile AuExtension.m".to_string());
    }

    let status = Command::new("ar")
        .args(["rcs", extension_lib.to_str().unwrap(), extension_obj.to_str().unwrap()])
        .status()
        .map_err(|e| format!("Failed to create static library: {}", e))?;

    if !status.success() {
        return Err("Failed to create AuExtension static library".to_string());
    }

    // Clean up object files
    let _ = fs::remove_file(&wrapper_obj);
    let _ = fs::remove_file(&extension_obj);

    Ok(gen_dir)
}

/// Read version from workspace Cargo.toml and convert to Apple's version integer format
fn get_version_info(workspace_root: &Path) -> Result<(String, u32), String> {
    let cargo_toml_path = workspace_root.join("Cargo.toml");
    let cargo_toml = fs::read_to_string(&cargo_toml_path)
        .map_err(|e| format!("Failed to read Cargo.toml: {}", e))?;

    // Parse version from workspace.package.version
    let version = cargo_toml
        .lines()
        .skip_while(|line| !line.contains("[workspace.package]"))
        .skip(1)
        .find(|line| line.trim().starts_with("version"))
        .and_then(|line| line.split('=').nth(1))
        .map(|v| v.trim().trim_matches('"').to_string())
        .ok_or("Could not find version in Cargo.toml")?;

    // Parse version into major.minor.patch
    let parts: Vec<&str> = version.split('.').collect();
    if parts.len() < 3 {
        return Err(format!("Invalid version format: {}", version));
    }

    let major: u32 = parts[0].parse().map_err(|_| "Invalid major version")?;
    let minor: u32 = parts[1].parse().map_err(|_| "Invalid minor version")?;
    let patch: u32 = parts[2].parse().map_err(|_| "Invalid patch version")?;

    // Convert to Apple's version format: (major << 16) | (minor << 8) | patch
    let version_int = (major << 16) | (minor << 8) | patch;

    Ok((version, version_int))
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 3 || args[1] != "bundle" {
        print_usage();
        std::process::exit(1);
    }

    let package = &args[2];
    let release = args.iter().any(|a| a == "--release");
    let install = args.iter().any(|a| a == "--install");
    let clean = args.iter().any(|a| a == "--clean");
    let build_vst3 = args.iter().any(|a| a == "--vst3");
    let build_au = args.iter().any(|a| a == "--au");

    // Default to VST3 if no format specified
    let (build_vst3, build_au) = if !build_vst3 && !build_au {
        (true, false)
    } else {
        (build_vst3, build_au)
    };

    if let Err(e) = bundle(package, release, install, clean, build_vst3, build_au) {
        eprintln!("Error: {}", e);
        std::process::exit(1);
    }
}

fn print_usage() {
    eprintln!("Usage: cargo xtask bundle <package> [--vst3] [--au] [--release] [--install] [--clean]");
    eprintln!();
    eprintln!("Commands:");
    eprintln!("  bundle    Build and bundle a plugin");
    eprintln!();
    eprintln!("Formats:");
    eprintln!("  --vst3    Build VST3 bundle (default if no format specified)");
    eprintln!("  --au      Build Audio Unit bundle (AUv3 App Extension: .app with .appex)");
    eprintln!();
    eprintln!("Options:");
    eprintln!("  --release    Build in release mode");
    eprintln!("  --install    Install to system plugin directories");
    eprintln!("  --clean      Clean build caches before building (forces full rebuild)");
    eprintln!("               Removes beamer-au cc cache and previous app bundle.");
    eprintln!("               Use when ObjC/header changes aren't being picked up.");
    eprintln!();
    eprintln!("Examples:");
    eprintln!("  cargo xtask bundle gain --vst3 --release --install");
    eprintln!("  cargo xtask bundle gain --au --release --install");
    eprintln!("  cargo xtask bundle gain --au --release --clean");
}

/// Find beamer-au output directory for a given target and profile.
/// Returns None if not found (beamer-au not yet built).
fn find_beamer_au_out_dir(workspace_root: &Path, target: &str, profile: &str) -> Option<PathBuf> {
    let build_dir = workspace_root
        .join("target")
        .join(target)
        .join(profile)
        .join("build");

    if !build_dir.exists() {
        return None;
    }

    // Find beamer-au-* directory
    for entry in fs::read_dir(&build_dir).ok()? {
        let entry = entry.ok()?;
        let name = entry.file_name();
        if name.to_string_lossy().starts_with("beamer-au-") {
            let out_dir = entry.path().join("out");
            if out_dir.exists() {
                return Some(out_dir);
            }
        }
    }

    None
}

/// Generate RUSTFLAGS for linking AU static libraries.
///
/// The `objc_lib_dir` parameter points to where plugin-specific ObjC static libraries
/// were compiled (contains libplugin_au_objc.a and libplugin_au_extension.a).
fn get_au_rustflags(
    plugin_name: &str,
    objc_lib_dir: &Path,
) -> Result<String, String> {
    let objc_lib_dir_str = objc_lib_dir.to_str()
        .ok_or_else(|| "Invalid ObjC library directory path".to_string())?;

    // Generate plugin-specific class and function names
    let pascal_name = to_pascal_case(plugin_name);
    let wrapper_class = format!("Beamer{}AuWrapper", pascal_name);
    let extension_class = format!("Beamer{}AuExtension", pascal_name);
    let factory_func = format!("Beamer{}AuExtensionFactory", pascal_name);

    // Library names based on plugin
    let lib_name = plugin_name.replace('-', "_");

    // Build RUSTFLAGS with all necessary linker arguments
    // Note: beamer_au_appex_force_link is internal (not exported) to avoid symbol collisions
    let flags = [
        format!("-L native={}", objc_lib_dir_str),
        format!("-C link-arg=-Wl,-force_load,{}/lib{}_au_objc.a", objc_lib_dir_str, lib_name),
        format!("-C link-arg=-Wl,-force_load,{}/lib{}_au_extension.a", objc_lib_dir_str, lib_name),
        format!("-C link-arg=-Wl,-exported_symbol,_OBJC_CLASS_$_{}", wrapper_class),
        format!("-C link-arg=-Wl,-exported_symbol,_OBJC_CLASS_$_{}", extension_class),
        format!("-C link-arg=-Wl,-exported_symbol,_OBJC_METACLASS_$_{}", wrapper_class),
        format!("-C link-arg=-Wl,-exported_symbol,_OBJC_METACLASS_$_{}", extension_class),
        format!("-C link-arg=-Wl,-exported_symbol,_{}", factory_func),
    ];

    Ok(flags.join(" "))
}

/// Build beamer-au to ensure static libraries exist before building plugins.
fn ensure_beamer_au_built(workspace_root: &Path, target: &str, release: bool) -> Result<(), String> {
    let profile = if release { "release" } else { "debug" };

    // Check if already built
    if find_beamer_au_out_dir(workspace_root, target, profile).is_some() {
        return Ok(());
    }

    println!("Building beamer-au for {}...", target);
    let mut cmd = Command::new("cargo");
    cmd.arg("build")
        .arg("-p")
        .arg("beamer-au")
        .arg("--target")
        .arg(target)
        .current_dir(workspace_root);

    if release {
        cmd.arg("--release");
    }

    let status = cmd.status()
        .map_err(|e| format!("Failed to build beamer-au: {}", e))?;

    if !status.success() {
        return Err("Failed to build beamer-au".to_string());
    }

    Ok(())
}

fn build_universal(package: &str, release: bool, workspace_root: &Path) -> Result<PathBuf, String> {
    println!("Building universal binary (x86_64 + arm64)...");

    let profile = if release { "release" } else { "debug" };
    let lib_name = package.replace('-', "_");
    let dylib_name = format!("lib{}.dylib", lib_name);

    // Ensure beamer-au is built for both architectures first
    ensure_beamer_au_built(workspace_root, "x86_64-apple-darwin", release)?;
    ensure_beamer_au_built(workspace_root, "aarch64-apple-darwin", release)?;

    // Generate and compile plugin-specific ObjC code for both architectures
    println!("Generating plugin-specific ObjC for {}...", package);
    let objc_lib_dir_x86 = compile_plugin_objc(package, workspace_root, "x86_64-apple-darwin")?;
    let objc_lib_dir_arm = compile_plugin_objc(package, workspace_root, "aarch64-apple-darwin")?;

    // Build for x86_64
    println!("Building for x86_64...");
    let rustflags = get_au_rustflags(package, &objc_lib_dir_x86)?;
    let mut cmd = Command::new("cargo");
    cmd.arg("build")
        .arg("-p")
        .arg(package)
        .arg("--target")
        .arg("x86_64-apple-darwin")
        .env("RUSTFLAGS", &rustflags)
        .current_dir(workspace_root);

    if release {
        cmd.arg("--release");
    }

    let status = cmd.status().map_err(|e| format!("Failed to build for x86_64: {}", e))?;
    if !status.success() {
        return Err("Build for x86_64 failed".to_string());
    }

    // Build for arm64
    println!("Building for arm64...");
    let rustflags = get_au_rustflags(package, &objc_lib_dir_arm)?;
    let mut cmd = Command::new("cargo");
    cmd.arg("build")
        .arg("-p")
        .arg(package)
        .arg("--target")
        .arg("aarch64-apple-darwin")
        .env("RUSTFLAGS", &rustflags)
        .current_dir(workspace_root);

    if release {
        cmd.arg("--release");
    }

    let status = cmd.status().map_err(|e| format!("Failed to build for arm64: {}", e))?;
    if !status.success() {
        return Err("Build for arm64 failed".to_string());
    }

    // Paths to the built binaries
    let x86_64_path = workspace_root
        .join("target")
        .join("x86_64-apple-darwin")
        .join(profile)
        .join(&dylib_name);

    let arm64_path = workspace_root
        .join("target")
        .join("aarch64-apple-darwin")
        .join(profile)
        .join(&dylib_name);

    // Output path for universal binary
    let universal_path = workspace_root
        .join("target")
        .join(profile)
        .join(&dylib_name);

    // Create target directory if it doesn't exist
    if let Some(parent) = universal_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create target dir: {}", e))?;
    }

    // Combine using lipo
    println!("Creating universal binary with lipo...");
    let status = Command::new("lipo")
        .args([
            "-create",
            x86_64_path.to_str().unwrap(),
            arm64_path.to_str().unwrap(),
            "-output",
            universal_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run lipo: {}", e))?;

    if !status.success() {
        return Err("lipo failed to create universal binary".to_string());
    }

    println!("Universal binary created at: {}", universal_path.display());

    Ok(universal_path)
}

/// Clean build caches to force full rebuild.
///
/// This is necessary because:
/// 1. `cc::Build` (used in build.rs) caches compiled .o files in target/build/beamer-au-*/
/// 2. Even if cargo triggers a rebuild, cc may use cached object files
/// 3. The final .app bundle may not get updated if only static libraries changed
///
/// Use --clean when ObjC or header file changes aren't being picked up.
fn clean_build_caches(workspace_root: &Path, package: &str, release: bool) -> Result<(), String> {
    println!("Cleaning build caches...");

    let profile = if release { "release" } else { "debug" };
    let target_dir = workspace_root.join("target").join(profile);

    // Clean beamer-au cc cache (compiled ObjC objects)
    let build_dir = workspace_root.join("target").join(profile).join("build");
    if build_dir.exists() {
        for entry in fs::read_dir(&build_dir).map_err(|e| e.to_string())? {
            let entry = entry.map_err(|e| e.to_string())?;
            let name = entry.file_name();
            if name.to_string_lossy().starts_with("beamer-au-") {
                println!("  Removing: {}", entry.path().display());
                fs::remove_dir_all(entry.path()).map_err(|e| e.to_string())?;
            }
        }
    }

    // Clean beamer-au deps (compiled Rust library)
    let deps_dir = target_dir.join("deps");
    if deps_dir.exists() {
        for entry in fs::read_dir(&deps_dir).map_err(|e| e.to_string())? {
            let entry = entry.map_err(|e| e.to_string())?;
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with("libbeamer_au") {
                println!("  Removing: {}", entry.path().display());
                fs::remove_file(entry.path()).map_err(|e| e.to_string())?;
            }
        }
    }

    // Clean previous app bundle
    let bundle_name = to_au_bundle_name(package);
    let app_path = target_dir.join(&bundle_name);
    if app_path.exists() {
        println!("  Removing: {}", app_path.display());
        fs::remove_dir_all(&app_path).map_err(|e| e.to_string())?;
    }

    println!("Clean complete.");
    Ok(())
}

fn bundle(
    package: &str,
    release: bool,
    install: bool,
    clean: bool,
    build_vst3: bool,
    build_au: bool,
) -> Result<(), String> {
    println!("Bundling {} (release: {})...", package, release);

    // Get workspace root
    let workspace_root = get_workspace_root()?;

    // Clean build caches if requested
    if clean {
        clean_build_caches(&workspace_root, package, release)?;
    }

    // For macOS AU, build universal binary (x86_64 + arm64)
    let universal = build_au && cfg!(target_os = "macos");

    // Determine paths
    let profile = if release { "release" } else { "debug" };
    let target_dir = workspace_root.join("target").join(profile);

    let dylib_path = if universal {
        build_universal(package, release, &workspace_root)?
    } else {
        // Build the plugin for current architecture
        println!("Building...");
        let mut cmd = Command::new("cargo");
        cmd.arg("build")
            .arg("-p")
            .arg(package)
            .current_dir(&workspace_root);

        if release {
            cmd.arg("--release");
        }

        let status = cmd.status().map_err(|e| format!("Failed to run cargo: {}", e))?;
        if !status.success() {
            return Err("Build failed".to_string());
        }

        // Convert package name to library name (replace hyphens with underscores)
        let lib_name = package.replace('-', "_");

        // Find the dylib
        let dylib_name = format!("lib{}.dylib", lib_name);
        let dylib_path = target_dir.join(&dylib_name);

        if !dylib_path.exists() {
            return Err(format!("Built library not found: {}", dylib_path.display()));
        }

        dylib_path
    };

    // Build requested formats
    if build_vst3 {
        bundle_vst3(package, &target_dir, &dylib_path, install)?;
    }

    if build_au {
        bundle_au(package, &target_dir, &dylib_path, install, &workspace_root)?;
    }

    Ok(())
}

fn bundle_vst3(
    package: &str,
    target_dir: &Path,
    dylib_path: &Path,
    install: bool,
) -> Result<(), String> {
    // Create bundle name (convert to CamelCase and add .vst3)
    let bundle_name = to_vst3_bundle_name(package);
    let bundle_dir = target_dir.join(&bundle_name);

    // Create bundle directory structure
    let contents_dir = bundle_dir.join("Contents");
    let macos_dir = contents_dir.join("MacOS");
    let resources_dir = contents_dir.join("Resources");

    println!("Creating VST3 bundle at {}...", bundle_dir.display());

    // Clean up existing bundle
    if bundle_dir.exists() {
        fs::remove_dir_all(&bundle_dir).map_err(|e| format!("Failed to remove old bundle: {}", e))?;
    }

    // Create directories
    fs::create_dir_all(&macos_dir).map_err(|e| format!("Failed to create MacOS dir: {}", e))?;
    fs::create_dir_all(&resources_dir)
        .map_err(|e| format!("Failed to create Resources dir: {}", e))?;

    // Copy dylib
    let plugin_binary = macos_dir.join(bundle_name.trim_end_matches(".vst3"));
    fs::copy(dylib_path, &plugin_binary)
        .map_err(|e| format!("Failed to copy dylib: {}", e))?;

    // Create Info.plist
    let info_plist = create_vst3_info_plist(package, &bundle_name);
    fs::write(contents_dir.join("Info.plist"), info_plist)
        .map_err(|e| format!("Failed to write Info.plist: {}", e))?;

    // Create PkgInfo
    fs::write(contents_dir.join("PkgInfo"), "BNDL????")
        .map_err(|e| format!("Failed to write PkgInfo: {}", e))?;

    println!("VST3 bundle created: {}", bundle_dir.display());

    // Install if requested
    if install {
        install_vst3(&bundle_dir, &bundle_name)?;
    }

    Ok(())
}

fn bundle_au(
    package: &str,
    target_dir: &Path,
    dylib_path: &Path,
    install: bool,
    workspace_root: &Path,
) -> Result<(), String> {
    // Create AUv3 .app bundle structure with .appex extension:
    // BeamerGain.app/                         # Container app
    // ├── Contents/
    // │   ├── Info.plist                      # Minimal app plist (LSUIElement=true)
    // │   ├── MacOS/
    // │   │   └── BeamerGain                  # Symlink to appex binary
    // │   ├── PlugIns/
    // │   │   └── BeamerGain.appex/           # The actual AU extension
    // │   │       ├── Contents/
    // │   │       │   ├── Info.plist          # NSExtension + AudioComponents
    // │   │       │   ├── MacOS/
    // │   │       │   │   └── BeamerGain      # Plugin dylib
    // │   │       │   └── Resources/
    // │   ├── Resources/
    // │   └── PkgInfo                         # "APPL????"

    // Get version from Cargo.toml
    let (version_string, version_int) = get_version_info(workspace_root)?;

    let bundle_name = to_au_bundle_name(package);
    let bundle_dir = target_dir.join(&bundle_name);
    let contents_dir = bundle_dir.join("Contents");
    let app_resources_dir = contents_dir.join("Resources");
    let plugins_dir = contents_dir.join("PlugIns");

    println!("Creating AUv3 app extension bundle at {}...", bundle_dir.display());

    // Clean up existing bundle
    if bundle_dir.exists() {
        fs::remove_dir_all(&bundle_dir).map_err(|e| format!("Failed to remove old bundle: {}", e))?;
    }

    // Create app directories
    let app_macos_dir = contents_dir.join("MacOS");
    let frameworks_dir = contents_dir.join("Frameworks");
    fs::create_dir_all(&app_macos_dir).map_err(|e| format!("Failed to create app MacOS dir: {}", e))?;
    fs::create_dir_all(&app_resources_dir).map_err(|e| format!("Failed to create app Resources dir: {}", e))?;
    fs::create_dir_all(&plugins_dir).map_err(|e| format!("Failed to create PlugIns dir: {}", e))?;
    fs::create_dir_all(&frameworks_dir).map_err(|e| format!("Failed to create Frameworks dir: {}", e))?;

    // Create the .appex bundle structure
    let executable_name = bundle_name.trim_end_matches(".app");
    let appex_name = format!("{}.appex", executable_name);
    let appex_dir = plugins_dir.join(&appex_name);
    let appex_contents_dir = appex_dir.join("Contents");
    let appex_macos_dir = appex_contents_dir.join("MacOS");
    let appex_resources_dir = appex_contents_dir.join("Resources");

    fs::create_dir_all(&appex_macos_dir).map_err(|e| format!("Failed to create appex MacOS dir: {}", e))?;
    fs::create_dir_all(&appex_resources_dir).map_err(|e| format!("Failed to create appex Resources dir: {}", e))?;

    // Create framework bundle for in-process AU loading on macOS.
    // Use versioned framework structure (standard macOS framework layout):
    // Framework.framework/
    // ├── Framework -> Versions/Current/Framework  (symlink)
    // ├── Resources -> Versions/Current/Resources  (symlink)
    // └── Versions/
    //     ├── A/
    //     │   ├── Framework (binary)
    //     │   ├── Resources/
    //     │   │   └── Info.plist
    //     │   └── _CodeSignature/
    //     └── Current -> A  (symlink)
    let framework_name = format!("{}AU", executable_name);
    let framework_bundle_id = format!("com.beamer.{}.framework", package);
    let framework_dir = frameworks_dir.join(format!("{}.framework", framework_name));

    // Create versioned directory structure
    let versions_dir = framework_dir.join("Versions");
    let version_a_dir = versions_dir.join("A");
    let version_a_resources = version_a_dir.join("Resources");
    fs::create_dir_all(&version_a_resources)
        .map_err(|e| format!("Failed to create framework Versions/A/Resources dir: {}", e))?;

    // Copy dylib to Versions/A/
    let framework_binary = version_a_dir.join(&framework_name);
    fs::copy(dylib_path, &framework_binary)
        .map_err(|e| format!("Failed to copy dylib to framework: {}", e))?;

    // Fix dylib install name to use @rpath with versioned path
    let _ = Command::new("install_name_tool")
        .args(["-id", &format!("@rpath/{}.framework/Versions/A/{}", framework_name, framework_name),
               framework_binary.to_str().unwrap()])
        .status();

    // Create framework Info.plist in Versions/A/Resources/
    let framework_plist = format!(r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>{framework_name}</string>
    <key>CFBundleIdentifier</key>
    <string>{bundle_id}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>{framework_name}</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleVersion</key>
    <string>{version}</string>
    <key>CFBundleShortVersionString</key>
    <string>{version}</string>
</dict>
</plist>
"#, framework_name = framework_name, bundle_id = framework_bundle_id, version = version_string);
    fs::write(version_a_resources.join("Info.plist"), framework_plist)
        .map_err(|e| format!("Failed to write framework Info.plist: {}", e))?;

    // Create symlinks for versioned framework structure
    // Versions/Current -> A
    #[cfg(unix)]
    {
        use std::os::unix::fs::symlink;
        let current_link = versions_dir.join("Current");
        let _ = fs::remove_file(&current_link); // Remove if exists
        symlink("A", &current_link)
            .map_err(|e| format!("Failed to create Versions/Current symlink: {}", e))?;

        // Framework root symlinks
        // Framework -> Versions/Current/Framework
        let binary_link = framework_dir.join(&framework_name);
        let _ = fs::remove_file(&binary_link);
        symlink(format!("Versions/Current/{}", framework_name), &binary_link)
            .map_err(|e| format!("Failed to create framework binary symlink: {}", e))?;

        // Resources -> Versions/Current/Resources
        let resources_link = framework_dir.join("Resources");
        let _ = fs::remove_file(&resources_link);
        symlink("Versions/Current/Resources", &resources_link)
            .map_err(|e| format!("Failed to create Resources symlink: {}", e))?;
    }

    println!("Created framework: {}.framework (versioned structure)", framework_name);

    // Build appex executable - thin wrapper that links the framework
    let appex_binary_path = appex_macos_dir.join(executable_name);

    // Generate plugin-specific appex_stub.m (no main function - uses NSExtensionMain)
    let appex_stub_source = generate_appex_stub_source(package);
    let appex_gen_dir = workspace_root.join("target/au-gen").join(package);
    fs::create_dir_all(&appex_gen_dir)
        .map_err(|e| format!("Failed to create appex gen dir: {}", e))?;
    let appex_stub_path = appex_gen_dir.join("appex_stub.m");
    fs::write(&appex_stub_path, appex_stub_source)
        .map_err(|e| format!("Failed to write appex_stub.m: {}", e))?;

    println!("Building appex executable (universal binary)...");

    // Build for x86_64
    let appex_x86_64_path = bundle_dir.join(format!("{}_x86_64", executable_name));
    let clang_status = Command::new("clang")
        .args([
            "-arch", "x86_64",
            "-fobjc-arc",
            "-fmodules",
            "-framework", "Foundation",
            "-framework", "AudioToolbox",
            "-framework", "AVFoundation",
            "-framework", "CoreAudio",
            "-F", frameworks_dir.to_str().unwrap(),
            "-framework", &framework_name,
            "-Wl,-rpath,@loader_path/../../../../Frameworks",
            "-Wl,-e,_NSExtensionMain",  // Use Apple's standard extension entry point
            "-o", appex_x86_64_path.to_str().unwrap(),
            appex_stub_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run clang for x86_64: {}", e))?;

    if !clang_status.success() {
        return Err("Failed to build appex for x86_64".to_string());
    }

    // Build for arm64
    let appex_arm64_path = bundle_dir.join(format!("{}_arm64", executable_name));
    let clang_status = Command::new("clang")
        .args([
            "-arch", "arm64",
            "-fobjc-arc",
            "-fmodules",
            "-framework", "Foundation",
            "-framework", "AudioToolbox",
            "-framework", "AVFoundation",
            "-framework", "CoreAudio",
            "-F", frameworks_dir.to_str().unwrap(),
            "-framework", &framework_name,
            "-Wl,-rpath,@loader_path/../../../../Frameworks",
            "-Wl,-e,_NSExtensionMain",  // Use Apple's standard extension entry point
            "-o", appex_arm64_path.to_str().unwrap(),
            appex_stub_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run clang for arm64: {}", e))?;

    if !clang_status.success() {
        return Err("Failed to build appex for arm64".to_string());
    }

    // Combine with lipo
    let lipo_status = Command::new("lipo")
        .args([
            "-create",
            appex_x86_64_path.to_str().unwrap(),
            appex_arm64_path.to_str().unwrap(),
            "-output",
            appex_binary_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run lipo for appex: {}", e))?;

    if !lipo_status.success() {
        return Err("Failed to create universal appex binary".to_string());
    }

    // Clean up intermediate binaries
    let _ = fs::remove_file(&appex_x86_64_path);
    let _ = fs::remove_file(&appex_arm64_path);

    println!("Appex executable built (universal)");

    // Auto-detect component type, manufacturer, and subtype from plugin source
    let (component_type, detected_manufacturer, detected_subtype) = detect_au_component_info(package, workspace_root);
    println!(
        "Detected AU: {} (manufacturer: {}, subtype: {})",
        component_type,
        detected_manufacturer.as_deref().unwrap_or("Bemr"),
        detected_subtype.as_deref().unwrap_or("auto")
    );

    // Create appex Info.plist with NSExtension (out-of-process/XPC mode)
    let appex_info_plist = create_appex_info_plist(&AppexPlistConfig {
        package,
        executable_name,
        component_type: &component_type,
        manufacturer: detected_manufacturer.as_deref(),
        subtype: detected_subtype.as_deref(),
        framework_bundle_id: &framework_bundle_id,
        version_string: &version_string,
        version_int,
    });
    fs::write(appex_contents_dir.join("Info.plist"), appex_info_plist)
        .map_err(|e| format!("Failed to write appex Info.plist: {}", e))?;

    // Create container app Info.plist
    let app_info_plist = create_app_info_plist(package, executable_name, &version_string);
    fs::write(contents_dir.join("Info.plist"), app_info_plist)
        .map_err(|e| format!("Failed to write app Info.plist: {}", e))?;

    // Create PkgInfo for app
    fs::write(contents_dir.join("PkgInfo"), "APPL????")
        .map_err(|e| format!("Failed to write PkgInfo: {}", e))?;

    // Build host app executable from C stub (universal binary).
    // This is a minimal stub that triggers pluginkit registration when launched.
    // The app is marked LSBackgroundOnly so it exits immediately after registration.
    println!("Building host app executable (universal)...");

    let stub_main_path = workspace_root.join("crates/beamer-au/objc/stub_main.c");
    let host_x86_64_path = bundle_dir.join(format!("{}_x86_64", executable_name));
    let host_arm64_path = bundle_dir.join(format!("{}_arm64", executable_name));
    let host_binary_dst = app_macos_dir.join(executable_name);

    // Build for x86_64
    let clang_status = Command::new("clang")
        .args([
            "-arch", "x86_64",
            "-framework", "Foundation",
            "-o", host_x86_64_path.to_str().unwrap(),
            stub_main_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run clang for x86_64: {}", e))?;

    if !clang_status.success() {
        return Err("Failed to build host app for x86_64".to_string());
    }

    // Build for arm64
    let clang_status = Command::new("clang")
        .args([
            "-arch", "arm64",
            "-framework", "Foundation",
            "-o", host_arm64_path.to_str().unwrap(),
            stub_main_path.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run clang for arm64: {}", e))?;

    if !clang_status.success() {
        return Err("Failed to build host app for arm64".to_string());
    }

    // Combine with lipo
    let lipo_status = Command::new("lipo")
        .args([
            "-create",
            host_x86_64_path.to_str().unwrap(),
            host_arm64_path.to_str().unwrap(),
            "-output",
            host_binary_dst.to_str().unwrap(),
        ])
        .status()
        .map_err(|e| format!("Failed to run lipo for host app: {}", e))?;

    if !lipo_status.success() {
        return Err("Failed to create universal host app binary".to_string());
    }

    // Clean up intermediate binaries
    let _ = fs::remove_file(&host_x86_64_path);
    let _ = fs::remove_file(&host_arm64_path);

    println!("Host app built (universal)");

    println!("AUv3 app extension bundle created: {}", bundle_dir.display());

    // Code sign framework first, then appex, then container app
    println!("Code signing framework...");
    let framework_sign_status = Command::new("codesign")
        .args(["--force", "--sign", "-", framework_dir.to_str().unwrap()])
        .status();

    match framework_sign_status {
        Ok(status) if status.success() => println!("Framework code signing successful"),
        Ok(_) => println!("Warning: Framework code signing failed"),
        Err(e) => println!("Warning: Could not run codesign on framework: {}", e),
    }

    println!("Code signing appex...");
    let entitlements_path = workspace_root.join("crates/beamer-au/resources/appex.entitlements");
    let appex_sign_status = Command::new("codesign")
        .args([
            "--force",
            "--sign", "-",
            "--entitlements", entitlements_path.to_str().unwrap(),
            appex_dir.to_str().unwrap()
        ])
        .status();

    match appex_sign_status {
        Ok(status) if status.success() => println!("Appex code signing successful"),
        Ok(_) => println!("Warning: Appex code signing failed"),
        Err(e) => println!("Warning: Could not run codesign on appex: {}", e),
    }

    println!("Code signing container app...");
    let app_sign_status = Command::new("codesign")
        .args(["--force", "--sign", "-", bundle_dir.to_str().unwrap()])
        .status();

    match app_sign_status {
        Ok(status) if status.success() => println!("Container app code signing successful"),
        Ok(_) => println!("Warning: Container app code signing failed"),
        Err(e) => println!("Warning: Could not run codesign on app: {}", e),
    }

    // Install if requested
    if install {
        install_au(&bundle_dir, &bundle_name)?;
    }

    Ok(())
}

/// Detect AU component type, manufacturer, and subtype from plugin source code.
///
/// Parses the plugin's lib.rs file looking for the `AuConfig::new()` declaration
/// to extract the ComponentType and fourcc codes.
///
/// Returns (component_type_code, manufacturer_option, subtype_option)
fn detect_au_component_info(package: &str, workspace_root: &Path) -> (String, Option<String>, Option<String>) {
    // Try to find the lib.rs for this package
    let lib_path = workspace_root.join("examples").join(package).join("src/lib.rs");

    if let Ok(content) = fs::read_to_string(&lib_path) {
        // Detect component type
        let component_type = if content.contains("ComponentType::MusicDevice")
            || content.contains("ComponentType::Generator")
        {
            "aumu".to_string()
        } else if content.contains("ComponentType::MidiProcessor") {
            "aumi".to_string()
        } else if content.contains("ComponentType::MusicEffect") {
            "aumf".to_string()
        } else {
            // Default to effect (aufx)
            "aufx".to_string()
        };

        // Detect manufacturer and subtype from fourcc!(b"xxxx") patterns
        // Pattern: AuConfig::new(type, fourcc!(b"manu"), fourcc!(b"subt"))
        let (manufacturer, subtype) = detect_au_fourcc_codes(&content);

        (component_type, manufacturer, subtype)
    } else {
        // Default to effect if we can't read the file
        ("aufx".to_string(), None, None)
    }
}

/// Extract AU fourcc codes (manufacturer and subtype) from plugin source code.
///
/// Looks for the pattern `fourcc!(b"xxxx")` which appears in
/// `AuConfig::new(ComponentType::..., fourcc!(b"manu"), fourcc!(b"subt"))`.
///
/// Returns (manufacturer, subtype) as Options.
fn detect_au_fourcc_codes(content: &str) -> (Option<String>, Option<String>) {
    // Find all fourcc!(b"xxxx") patterns
    let mut fourcc_codes: Vec<String> = Vec::new();

    let mut remaining = content;
    while let Some(start) = remaining.find("fourcc!(b\"") {
        let after_prefix = &remaining[start + 10..]; // Skip "fourcc!(b\""
        if let Some(end) = after_prefix.find('"') {
            let code = &after_prefix[..end];
            if code.len() == 4 && code.is_ascii() {
                fourcc_codes.push(code.to_string());
            }
        }
        // Move past this match to find next
        remaining = &remaining[start + 10..];
    }

    // In AuConfig::new(type, manufacturer, subtype):
    // - First fourcc! is manufacturer
    // - Second fourcc! is subtype
    let manufacturer = fourcc_codes.first().cloned();
    let subtype = fourcc_codes.get(1).cloned();
    (manufacturer, subtype)
}

fn get_workspace_root() -> Result<PathBuf, String> {
    let output = Command::new("cargo")
        .args(["locate-project", "--workspace", "--message-format=plain"])
        .output()
        .map_err(|e| format!("Failed to locate workspace: {}", e))?;

    if !output.status.success() {
        return Err("Failed to locate workspace".to_string());
    }

    let cargo_toml = String::from_utf8_lossy(&output.stdout);
    let path = PathBuf::from(cargo_toml.trim());
    path.parent()
        .map(|p| p.to_path_buf())
        .ok_or_else(|| "Invalid workspace path".to_string())
}

fn to_vst3_bundle_name(package: &str) -> String {
    // Convert package name to CamelCase bundle name with Beamer prefix
    // e.g., "gain" -> "BeamerGain.vst3", "midi-transform" -> "BeamerMidiTransform.vst3"
    let name: String = package
        .split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().chain(chars).collect(),
            }
        })
        .collect();
    format!("Beamer{}.vst3", name)
}

/// Returns app bundle name for AUv3
/// e.g., "gain" -> "BeamerGain.app"
fn to_au_bundle_name(package: &str) -> String {
    let name: String = package
        .split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().chain(chars).collect(),
            }
        })
        .collect();
    format!("Beamer{}.app", name)
}

fn create_vst3_info_plist(package: &str, bundle_name: &str) -> String {
    let executable_name = bundle_name.trim_end_matches(".vst3");

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleExecutable</key>
    <string>{}</string>
    <key>CFBundleIdentifier</key>
    <string>com.beamer.{}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>{}</string>
    <key>CFBundlePackageType</key>
    <string>BNDL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>0.2.0</string>
    <key>CFBundleShortVersionString</key>
    <string>0.2.0</string>
</dict>
</plist>
"#,
        executable_name, package, executable_name
    )
}

/// Create Info.plist for container app (stub executable that triggers pluginkit registration)
fn create_app_info_plist(package: &str, executable_name: &str, version: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleExecutable</key>
    <string>{executable}</string>
    <key>CFBundleIdentifier</key>
    <string>com.beamer.{package}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>{executable}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>{version}</string>
    <key>CFBundleShortVersionString</key>
    <string>{version}</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.13</string>
    <key>LSBackgroundOnly</key>
    <true/>
</dict>
</plist>
"#,
        executable = executable_name,
        package = package,
        version = version
    )
}

/// Map AU component type code to appropriate tags for Info.plist.
///
/// DAWs use these tags for plugin categorization.
fn get_au_tags(component_type: &str) -> &'static str {
    match component_type {
        "aufx" => "Effects",           // Audio effect
        "aumu" => "Synth",             // Music device/instrument
        "aumi" => "MIDI",              // MIDI processor
        "aumf" => "Effects",           // Music effect
        _ => "Effects",                // Default fallback
    }
}

/// Create Info.plist for appex with NSExtension
fn create_appex_info_plist(config: &AppexPlistConfig) -> String {
    let manufacturer = config.manufacturer.unwrap_or("Bemr");
    let subtype = config.subtype.map(|s| s.to_string()).unwrap_or_else(|| {
        let gen: String = config.package.chars().filter(|c| c.is_alphanumeric()).take(4).collect::<String>().to_lowercase();
        if gen.len() < 4 { format!("{:_<4}", gen) } else { gen }
    });

    // Get appropriate tags based on component type
    let tags = get_au_tags(config.component_type);

    // Generate plugin-specific extension class name (implements AUAudioUnitFactory)
    let pascal_name = to_pascal_case(config.package);
    let extension_class = format!("Beamer{}AuExtension", pascal_name);

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleExecutable</key>
    <string>{executable}</string>
    <key>CFBundleIdentifier</key>
    <string>com.beamer.{package}.audiounit</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>{executable}</string>
    <key>CFBundlePackageType</key>
    <string>XPC!</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>{version}</string>
    <key>CFBundleShortVersionString</key>
    <string>{version}</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.13</string>
    <key>NSExtension</key>
    <dict>
        <key>NSExtensionPointIdentifier</key>
        <string>com.apple.AudioUnit</string>
        <key>NSExtensionPrincipalClass</key>
        <string>{extension_class}</string>
        <key>NSExtensionAttributes</key>
        <dict>
            <key>AudioComponents</key>
            <array>
                <dict>
                    <key>type</key>
                    <string>{component_type}</string>
                    <key>subtype</key>
                    <string>{subtype}</string>
                    <key>manufacturer</key>
                    <string>{manufacturer}</string>
                    <key>name</key>
                    <string>Beamer: {executable}</string>
                    <key>sandboxSafe</key>
                    <true/>
                    <key>tags</key>
                    <array>
                        <string>{tags}</string>
                    </array>
                    <key>version</key>
                    <integer>{version_int}</integer>
                    <key>description</key>
                    <string>{executable} Audio Unit</string>
                </dict>
            </array>
            <key>AudioComponentBundle</key>
            <string>{framework_bundle_id}</string>
        </dict>
    </dict>
</dict>
</plist>
"#,
        executable = config.executable_name,
        package = config.package,
        extension_class = extension_class,
        manufacturer = manufacturer,
        component_type = config.component_type,
        subtype = subtype,
        tags = tags,
        framework_bundle_id = config.framework_bundle_id,
        version = config.version_string,
        version_int = config.version_int
    )
}

fn install_vst3(bundle_dir: &Path, bundle_name: &str) -> Result<(), String> {
    let home = std::env::var("HOME").map_err(|_| "HOME not set")?;
    let vst3_dir = PathBuf::from(home)
        .join("Library")
        .join("Audio")
        .join("Plug-Ins")
        .join("VST3");

    // Create VST3 directory if needed
    fs::create_dir_all(&vst3_dir).map_err(|e| format!("Failed to create VST3 dir: {}", e))?;

    let dest = vst3_dir.join(bundle_name);

    // Remove existing installation
    if dest.exists() {
        fs::remove_dir_all(&dest).map_err(|e| format!("Failed to remove old installation: {}", e))?;
    }

    // Copy bundle
    copy_dir_all(bundle_dir, &dest)?;

    println!("VST3 installed to: {}", dest.display());
    Ok(())
}

fn install_au(bundle_dir: &Path, bundle_name: &str) -> Result<(), String> {
    let home = std::env::var("HOME").map_err(|_| "HOME not set")?;

    // AUv3 app extensions must be installed as apps (not in Components folder).
    // The system discovers them when the containing app is launched.
    let au_dir = PathBuf::from(&home).join("Applications");

    // Create Applications directory if needed
    fs::create_dir_all(&au_dir).map_err(|e| format!("Failed to create Applications dir: {}", e))?;

    let dest = au_dir.join(bundle_name);

    // Remove existing installation
    if dest.exists() {
        fs::remove_dir_all(&dest).map_err(|e| format!("Failed to remove old installation: {}", e))?;
    }

    // Copy bundle
    copy_dir_all(bundle_dir, &dest)?;

    println!("AUv3 app extension installed to: {}", dest.display());

    // Launch the app briefly to trigger pluginkit registration.
    // AUv3 extensions are registered when their containing app is first launched.
    println!("Registering Audio Unit extension...");
    let _ = Command::new("open")
        .arg(&dest)
        .status();

    // Give the system a moment to register the extension
    std::thread::sleep(std::time::Duration::from_millis(500));

    // Terminate the background app (it has LSBackgroundOnly so it won't show UI)
    let executable_name = bundle_name.trim_end_matches(".app");
    let _ = Command::new("killall")
        .arg(executable_name)
        .status();

    // Also refresh AU cache
    let _ = Command::new("killall")
        .arg("-9")
        .arg("AudioComponentRegistrar")
        .status();

    println!("Audio Unit registered successfully");

    Ok(())
}

fn copy_dir_all(src: &Path, dst: &Path) -> Result<(), String> {
    fs::create_dir_all(dst).map_err(|e| format!("Failed to create dir: {}", e))?;

    for entry in fs::read_dir(src).map_err(|e| format!("Failed to read dir: {}", e))? {
        let entry = entry.map_err(|e| format!("Failed to read entry: {}", e))?;
        let ty = entry
            .file_type()
            .map_err(|e| format!("Failed to get file type: {}", e))?;

        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if ty.is_dir() {
            copy_dir_all(&src_path, &dst_path)?;
        } else if ty.is_symlink() {
            // Preserve symlinks (important for AUv3 container app binary)
            #[cfg(unix)]
            {
                let target = fs::read_link(&src_path)
                    .map_err(|e| format!("Failed to read symlink: {}", e))?;
                std::os::unix::fs::symlink(&target, &dst_path)
                    .map_err(|e| format!("Failed to create symlink: {}", e))?;
            }
            #[cfg(not(unix))]
            {
                fs::copy(&src_path, &dst_path)
                    .map_err(|e| format!("Failed to copy file: {}", e))?;
            }
        } else {
            fs::copy(&src_path, &dst_path)
                .map_err(|e| format!("Failed to copy file: {}", e))?;
        }
    }

    Ok(())
}
